version: '3.8'
services:
  api:
    build: .
    ports:
      - 4000:4000
    networks:
      - app-network
    volumes:
      - ./src/:/app/src/
      - .env.docker/:/app/.env
    restart: unless-stopped
    depends_on: 
      - mongo
      - redis
      - postgres
  mongo:
    image: mongo:6.0.3
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: example
    volumes:
      - dbdata:/data/mongodb
    restart: unless-stopped
    networks:
      - app-network
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example
    ports:
      - '5432:5432'
    volumes: 
      - dbdata:/data/postgresql
    networks:
      - app-network
  redis:
    image: "redis:7.0.5"
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    name: app-network
    driver: bridge
volumes:
  dbdata: